main: uppaper.plugin.UpPaperPlugin
name: UpPaper
version: "1.0.0/260722"
dncore: 6.1.0
description: "PaperMC アップデート通知 プラグイン"
website: https://github.com/Necnion8/UpPaper

authors:
  - Necnion8

softdepends:
  - TimerLib
